### ISSUE TITLE
Exception thrown on any edit operation in IntelliJ IDEA 2017.3

### ISSUE THREAD

**Issue by VladRassokhin** [exbin/deltahex-intellij-plugin#3]
```
Unknown property name: 'modified'. Must be one of: VirtualFile.PROP_NAME, VirtualFile.PROP_ENCODING, VirtualFile.PROP_WRITABLE, VirtualFile.PROP_HIDDEN, VirtualFile.PROP_SYMLINK_TARGET
java.lang.IllegalArgumentException: Unknown property name: 'modified'. Must be one of: VirtualFile.PROP_NAME, VirtualFile.PROP_ENCODING, VirtualFile.PROP_WRITABLE, VirtualFile.PROP_HIDDEN, VirtualFile.PROP_SYMLINK_TARGET
	at com.intellij.openapi.vfs.newvfs.events.VFilePropertyChangeEvent.checkPropertyValuesCorrect(VFilePropertyChangeEvent.java:78)
	at com.intellij.openapi.vfs.newvfs.events.VFilePropertyChangeEvent.<init>(VFilePropertyChangeEvent.java:46)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl$2$1.run(VirtualFileManagerImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl$2.run(VirtualFileManagerImpl.java:191)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Plugin version is 0.1.5

IDE info:
IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.25, built on January 15, 2018
Licensed to JetBrains Team / Vladislav Rassokhin
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.12-gentoo

**Comment by hajdam** [comment]
Hi, thanks for reporting this issue. It is caused by some forgotten testing code while trying to introduce "document modified" behavior for changed files.

I tried to change this code. You can try updated testing version 0.1.6-SNAPSHOT if you wish:
http://deltahex.exbin.org/download.php?deltahex-intellij-plugin.jar

**Comment by VladRassokhin** [comment]
Update works fine

**Comment by hajdam** [comment]
Version 0.1.6 released.
